server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: ${LOG_LEVEL:info}

spring:
  application:
    name: springboot-helloworld
